media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: author
    path: _author.md
    type: file
    label: Author
    fields:
      - name: authorname
        type: select
        options:
          values:
          - value: bob
            label: Bob Smith
          - value: patricia
            label: Patricia Wills
          - value: alice
            label: Alice Brown
      - name: contact
        label: Contact information
        type: object
        list: true
        fields:
          - name: first_name
            type: string
          - name: last_name
            type: string
          - name: email
            type: string
          - name: phone
            type: string
          - { name: sightings, label: Sightings, type: image, list: true }
          - { name: tags, label: Tags, type: string, list: true }
  - name: modules
    label: Modules
    type: collection
    path: _modules
    view:
      fields: [ module_name, description, date ]
    fields:
      - name: module
        type: object
        label: Module
        fields:
          - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
          - {name: module_name,
            required: true,
            label: Module Name,
            type: string
            }
            
          - name: module_instructors
            label: Instructors
            type: string
            list: true
          - {name: description,
            required: true,
            label: Description,
            type: string,
            options: {
              minlength: 0,
              maxlength: 250
            }}
          - name: module_sections
            label: Module Sections
            type: object
            list: true
            fields:
              - name: module_name
                type: string
              - name: module_page 
                type: rich-text
  - name: module
    type: file
    path: _module.md
    label: Module
    fields:
      - name: module_name
        label: Module Name
        type: string
      - name: module_instructors
        label: Instructors
        type: string
        list: true
      - name: description
        label: Description
        type: string
        options:
          minlength: 0
          maxlength: 250
      - name: module_sections
        label: Module Sections
        type: object
        list: true
        fields:
          - name: module_name
            type: string
          - name: module_page 
            type: rich-text
          
  - name: resources
    path: _resources.md
    label: Resources
    type: file
    fields:
      - name: resource_blocks
        label: Resource Blocks
        type: object
        list: true
        fields:
          - name: block_name
            type: string
          - name: resources
            type: string
            list: true